### PR TITLE
Update dw-runtime-functions-orelse.adoc

### PR DESCRIPTION
**Pull request by tonedef71**

### CODE REVIEW

**Comment by dukesphere** [comment]
Hi, @tonedef71 , Thx for noticing this error and proposing a fix. Would you please sign the CLA above so that we can merge your suggestions the next time you contribute. We'll create a new PR for this so that we can get the fix in right away. Thanks again for your contribution!

**Comment by dukesphere** [comment]
https://github.com/mulesoft/docs-dataweave/pull/108

**Comment by tonedef71** [comment]
> Hi, @tonedef71 , Thx for noticing this error and proposing a fix. Would you please sign the CLA above so that we can merge your suggestions the next time you contribute. We'll create a new PR for this so that we can get the fix in right away. Thanks again for your contribution!

Odd.  I saw the following after I signed the CLA:
image

**Comment by dukesphere** [comment]
good to know!

**Pull request closed without merging**
